name = "zolagray"
description = "Zolagray is a theme for the modern developer. Clean and Minimal."
homepage = "https://github.com/bash-win/zolagray"
min_version = "0.23.0"
license = "MIT"
tags = ["dark", "blog", "responsive", "syntax-highlighting"]

[author]
name = "bash-win"
