base_url = "https://bash-win.github.io/zolagray"
title = "Zolagray"
description = "A demo site for the Zolagray theme."
compile_sass = true
generate_feeds = true
feed_limit = 10
feed_filenames = ["atom.xml"]
taxonomies = [{ name = "tags" }]

[markdown.highlighting]
theme = "catppuccin-mocha" # Code highlighting theme

[extra.zolagray]
theme = "iron"
home_list_latest_blog_posts = true
google_analytics_id = ""
ko_fi_url = ""
